import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar_SA': {
          'Login': 'تسجيل الدخول',
          'SendCode': 'إرسال الكود',
          'PLZEnterCode':
              'من فضلك قم بإدخال كود التحقق المرسل من خلال رسالة نصية ',
          'VerifyCode': 'كـود التحقق',
          'ResendPeriodic': 'إعادة الإرسال خلال  ',
          'Setting': 'الإعدادات',
          'Nodata': 'لا توجد بيانات',
          'Home': 'الرئيسية',
          'Prints': 'المطبوعات',
          'Reserves': 'الحجوزات',
          'MyAccount': 'حسابى',
          'ContactUs': 'اتصل بنا',
          'Search': 'بحـث',
          'Categories': 'الفئات',
          'ShowAll': 'عرض الكل',
          'MostSoldFrames': 'الفريمات الأكثر مبيعا',
          'MostReqFrames': 'الفريمات الأكثر طلبا',
          'LastUpdates': 'آخر التحديثات',
          'Myorders': 'طلباتى',
          'Mypoints': 'نقاطى',
          'ShareApp': 'شارك التطبيق',
          'TermsConditions': 'الشروط والاحكام',
          'Logout': 'تسجيل الخروج',
          'CurrentOrders': 'طلباتى الحالية',
          'PrevOrders': 'طلباتى السابقة',
          'RS': 'ر.س',
          'Layers': 'اللوحات',
          'Albums': 'الألبومات',
          'Papers': 'الورق',
          'Graduates': 'حفلات',
          'Wedding': 'زفاف',
          'Trades': 'تجارى',
          'Births': 'مواليد',
          'Model': 'موديل',
          'Cinema': 'سينيمائى',
          'Date': 'التاريخ',
          'Time': 'الوقت',
          'From': ' من ',
          'To': ' الى ',
          'City': ' المدينة ',
          'Hall': ' القاعة ',
          'Note': ' ملاحظة ',
          'NoteText': ' تضاف للمناطق خارج الاحساء رسوم النقل ',
          'Reserve': ' حجز ',
          'Name': ' الاسم ',
        },
        'en_US': {
          'Login': 'Login',
          'SendCode': 'Send Code',
          'PLZEnterCode':
              'Pleaze enter verification code which sent by text message',
          'VerifyCode': 'Verification Code',
          'ResendPeriodic': 'Resend in ',
          'Setting': 'Settings',
          'Nodata': 'Empty data',
          'Home': 'Home',
          'Prints': 'Prints',
          'Reserves': 'Reserves',
          'MyAccount': 'My Account',
          'ContactUs': 'Contact Us',
          'Search': 'Search',
          'Categories': 'Categories',
          'ShowAll': 'Show All',
          'MostSoldFrames': 'Most sold frames',
          'MostReqFrames': 'Most required frames',
          'LastUpdates': 'Recent updates',
          'Myorders': 'My Orders',
          'Mypoints': 'My Points',
          'ShareApp': 'Share App',
          'TermsConditions': 'Terms & Conditions',
          'Logout': 'Log Out',
          'CurrentOrders': 'Current Orders',
          'PrevOrders': 'Prevoius Orders',
          'RS': 'S.R',
          'Layers': 'Paints',
          'Albums': 'Albums',
          'Papers': 'Papers',
          'Graduates': 'Parts',
          'Wedding': 'Wedding',
          'Trades': 'Trades',
          'Births': 'Births',
          'Model': 'Models',
          'Cinema': 'Cinema',
          'Date': 'Date',
          'Time': 'Time',
          'From': ' From ',
          'To': ' To ',
          'City': ' City ',
          'Hall': ' Hall ',
          'Note': ' Note ',
          'NoteText': ' Transport fee for outside regions ',
          'Reserve': ' Reserve ',
          'Name': ' Name ',
        },
      };
}
